meta_product_name: "SEKOYA"
meta_title: "SEKOYA - SEKOYA réinvente l'aide à domicile"
meta_description: "Nos seniors sont toujours zen après le passage de nos helpers"
meta_image: "seko_banner.png" # should exist in `app/assets/images/`
twitter_account: "@anthony4213"   # required for Twitter Cards
